// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: config_recs.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigFileRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,1,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfigFileRequest) Reset() {
	*x = ConfigFileRequest{}
	mi := &file_config_recs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigFileRequest) ProtoMessage() {}

func (x *ConfigFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_recs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigFileRequest) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *ConfigFileRequest) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ConfigFileRequest) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConfigFileRequest) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

type ConfigFileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data []byte
}

func (b0 ConfigFileRequest_builder) Build() *ConfigFileRequest {
	m0 := &ConfigFileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

type ConfigStringRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        *string                `protobuf:"bytes,1,opt,name=data"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfigStringRequest) Reset() {
	*x = ConfigStringRequest{}
	mi := &file_config_recs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigStringRequest) ProtoMessage() {}

func (x *ConfigStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_recs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigStringRequest) GetData() string {
	if x != nil {
		if x.xxx_hidden_Data != nil {
			return *x.xxx_hidden_Data
		}
		return ""
	}
	return ""
}

func (x *ConfigStringRequest) SetData(v string) {
	x.xxx_hidden_Data = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ConfigStringRequest) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConfigStringRequest) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

type ConfigStringRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data *string
}

func (b0 ConfigStringRequest_builder) Build() *ConfigStringRequest {
	m0 := &ConfigStringRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Data = b.Data
	}
	return m0
}

type RecsResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Recs        *string                `protobuf:"bytes,1,opt,name=recs"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RecsResponse) Reset() {
	*x = RecsResponse{}
	mi := &file_config_recs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecsResponse) ProtoMessage() {}

func (x *RecsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_recs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecsResponse) GetRecs() string {
	if x != nil {
		if x.xxx_hidden_Recs != nil {
			return *x.xxx_hidden_Recs
		}
		return ""
	}
	return ""
}

func (x *RecsResponse) SetRecs(v string) {
	x.xxx_hidden_Recs = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RecsResponse) HasRecs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RecsResponse) ClearRecs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Recs = nil
}

type RecsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Recs *string
}

func (b0 RecsResponse_builder) Build() *RecsResponse {
	m0 := &RecsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Recs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Recs = b.Recs
	}
	return m0
}

var File_config_recs_proto protoreflect.FileDescriptor

const file_config_recs_proto_rawDesc = "" +
	"\n" +
	"\x11config_recs.proto\x12\x16parse.go_config_parser\"'\n" +
	"\x11ConfigFileRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\")\n" +
	"\x13ConfigStringRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"\"\n" +
	"\fRecsResponse\x12\x12\n" +
	"\x04recs\x18\x01 \x01(\tR\x04recs2\xe7\x01\n" +
	"\x11ConfigRecsService\x12f\n" +
	"\x13GetConfigRecsByFile\x12).parse.go_config_parser.ConfigFileRequest\x1a$.parse.go_config_parser.RecsResponse\x12j\n" +
	"\x15GetConfigRecsByString\x12+.parse.go_config_parser.ConfigStringRequest\x1a$.parse.go_config_parser.RecsResponseB4Z2github.com/noedaka/go-config-parser/internal/protob\beditionsp\xe8\a"

var file_config_recs_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_config_recs_proto_goTypes = []any{
	(*ConfigFileRequest)(nil),   // 0: parse.go_config_parser.ConfigFileRequest
	(*ConfigStringRequest)(nil), // 1: parse.go_config_parser.ConfigStringRequest
	(*RecsResponse)(nil),        // 2: parse.go_config_parser.RecsResponse
}
var file_config_recs_proto_depIdxs = []int32{
	0, // 0: parse.go_config_parser.ConfigRecsService.GetConfigRecsByFile:input_type -> parse.go_config_parser.ConfigFileRequest
	1, // 1: parse.go_config_parser.ConfigRecsService.GetConfigRecsByString:input_type -> parse.go_config_parser.ConfigStringRequest
	2, // 2: parse.go_config_parser.ConfigRecsService.GetConfigRecsByFile:output_type -> parse.go_config_parser.RecsResponse
	2, // 3: parse.go_config_parser.ConfigRecsService.GetConfigRecsByString:output_type -> parse.go_config_parser.RecsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_config_recs_proto_init() }
func file_config_recs_proto_init() {
	if File_config_recs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_recs_proto_rawDesc), len(file_config_recs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_recs_proto_goTypes,
		DependencyIndexes: file_config_recs_proto_depIdxs,
		MessageInfos:      file_config_recs_proto_msgTypes,
	}.Build()
	File_config_recs_proto = out.File
	file_config_recs_proto_goTypes = nil
	file_config_recs_proto_depIdxs = nil
}
