// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: config_recs.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigRecsService_GetConfigRecsByString_FullMethodName = "/parse.go_config_parser.ConfigRecsService/GetConfigRecsByString"
)

// ConfigRecsServiceClient is the client API for ConfigRecsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigRecsServiceClient interface {
	GetConfigRecsByString(ctx context.Context, in *ConfigStringRequest, opts ...grpc.CallOption) (*RecsResponse, error)
}

type configRecsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigRecsServiceClient(cc grpc.ClientConnInterface) ConfigRecsServiceClient {
	return &configRecsServiceClient{cc}
}

func (c *configRecsServiceClient) GetConfigRecsByString(ctx context.Context, in *ConfigStringRequest, opts ...grpc.CallOption) (*RecsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecsResponse)
	err := c.cc.Invoke(ctx, ConfigRecsService_GetConfigRecsByString_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigRecsServiceServer is the server API for ConfigRecsService service.
// All implementations must embed UnimplementedConfigRecsServiceServer
// for forward compatibility.
type ConfigRecsServiceServer interface {
	GetConfigRecsByString(context.Context, *ConfigStringRequest) (*RecsResponse, error)
	mustEmbedUnimplementedConfigRecsServiceServer()
}

// UnimplementedConfigRecsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigRecsServiceServer struct{}

func (UnimplementedConfigRecsServiceServer) GetConfigRecsByString(context.Context, *ConfigStringRequest) (*RecsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfigRecsByString not implemented")
}
func (UnimplementedConfigRecsServiceServer) mustEmbedUnimplementedConfigRecsServiceServer() {}
func (UnimplementedConfigRecsServiceServer) testEmbeddedByValue()                           {}

// UnsafeConfigRecsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigRecsServiceServer will
// result in compilation errors.
type UnsafeConfigRecsServiceServer interface {
	mustEmbedUnimplementedConfigRecsServiceServer()
}

func RegisterConfigRecsServiceServer(s grpc.ServiceRegistrar, srv ConfigRecsServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigRecsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigRecsService_ServiceDesc, srv)
}

func _ConfigRecsService_GetConfigRecsByString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigRecsServiceServer).GetConfigRecsByString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigRecsService_GetConfigRecsByString_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigRecsServiceServer).GetConfigRecsByString(ctx, req.(*ConfigStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigRecsService_ServiceDesc is the grpc.ServiceDesc for ConfigRecsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigRecsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "parse.go_config_parser.ConfigRecsService",
	HandlerType: (*ConfigRecsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfigRecsByString",
			Handler:    _ConfigRecsService_GetConfigRecsByString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config_recs.proto",
}
